#!/usr/bin/env bash
# shellcheck disable=SC2154
set -euEo pipefail

readonly BASE_PATH="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$BASE_PATH"

[[ ! -f ./.env ]] && cp --verbose ./.env{.sample,}

set -o allexport
. ./.env
set +o allexport

# Install brew
wget -qO - https://git.io/JTlbH?=brew-ubuntu | bash

brew install pre-commit
brew install shfmt
brew install shellcheck

# Add git hooks
(
  cd .git/hooks
  cp -sf ../../scripts/git-hooks/* .
)

sudo apt-get update -y
sudo apt-get install -y uuid-runtime
sudo apt-get install -y git-crypt

# Install Vagrant
type -P vagrant || wget -qO - "${iscript}/vagrant/vagrant-ubuntu" | bash
## vagrant plugins
vagrant plugin install vagrant-aws
vagrant plugin install vagrant-readenv
## vagrant boxes
vagrant box add dummy https://github.com/mitchellh/vagrant-aws/raw/master/dummy.box || :

cat <<-EOF

Edit your config:
\$ vim ./.env
EOF
